### ISSUE TITLE
Update Package To Use New autocomplete-plus API

### ISSUE THREAD

**Issue by joefitzgerald** [rsense/atom-rsense#1]
Please:
- Don't depend on autocomplete-plus in your package.json
- Switch to using an editor instead of an editorView during registration
- Don't use ProviderPackageFactory - it's redundant / nonexistent

Updated example: https://github.com/atom-community/autocomplete-plus/wiki/Tutorial:-Registering-and-creating-a-suggestion-provider

**Comment by joefitzgerald** [comment]
Further to above, please switch to the new API: https://github.com/atom-community/autocomplete-plus/wiki/Provider-API

**Comment by joefitzgerald** [comment]
The old API will be removed on Tuesday, February 10th, 2015. Please update to the new API by that time, or let me know if you have issues with the timeline.

**Comment by tylerdiaz** [comment]
@edubkendo Production version of this package is broken. Could this be looked at, please?

**Comment by brodock** [comment]
:+1:
